export const skills = [
	{
		technology: 'JavaScript',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
		alt: 'JavaScript logo',
	},
	{
		technology: 'TypeScript',
		proficiency: 'Beginner',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
		alt: 'TypeScript logo',
	},
	{
		technology: 'React',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
		alt: 'React logo',
	},
	{
		technology: 'NEXT',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg',
		alt: 'NEXT logo',
	},
	{
		technology: 'Bootstrap',
		proficiency: 'Advanced',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg',
		alt: 'Bootstrap logo',
	},
	{
		technology: 'Tailwind',
		proficiency: 'Advanced',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
		alt: 'Tailwind logo',
	},
	{
		technology: 'HTML',
		proficiency: 'Advanced',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
		alt: 'HTML logo',
	},
	{
		technology: 'Sass',
		proficiency: 'Advanced',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
		alt: 'Sass logo',
	},
	{
		technology: 'Git',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg',
		alt: 'Git logo',
	},
	{
		technology: 'MySQL',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg',
		alt: 'MySQL logo',
	},
	{
		technology: 'PHP',
		proficiency: 'Beginner',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-plain.svg',
		alt: 'PHP logo',
	},
	{
		technology: 'Adobe Illustrator',
		proficiency: 'Advanced',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/illustrator/illustrator-plain.svg',
		alt: 'Adobe Illustrator logo',
	},
	{
		technology: 'Adobe Photoshop',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-plain.svg',
		alt: 'Adobe Photoshop logo',
	},
	{
		technology: 'Figma',
		proficiency: 'Intermediate',
		icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
		alt: 'Figma logo',
	},
]
